// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5kPjw4esTbYMQLrHvJ0TtI-dnvQZrygw',
    appId: '1:1019726805573:web:0b5a59aef6081d7fb4812c',
    messagingSenderId: '1019726805573',
    projectId: 'my-barberia-7aa2a',
    authDomain: 'my-barberia-7aa2a.firebaseapp.com',
    storageBucket: 'my-barberia-7aa2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYlp3L4IGBTGsONCuyAD5nJh8dcfigdyc',
    appId: '1:1019726805573:android:00df8863e30aa3f3b4812c',
    messagingSenderId: '1019726805573',
    projectId: 'my-barberia-7aa2a',
    storageBucket: 'my-barberia-7aa2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAphAs7U_6z1uf9w0YA7KinBOignESWRCU',
    appId: '1:1019726805573:ios:a87d1d16c79a564fb4812c',
    messagingSenderId: '1019726805573',
    projectId: 'my-barberia-7aa2a',
    storageBucket: 'my-barberia-7aa2a.firebasestorage.app',
    iosClientId: '1019726805573-tcm0dlmorlpn990lbr6tv9ijp2nuaku9.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAphAs7U_6z1uf9w0YA7KinBOignESWRCU',
    appId: '1:1019726805573:ios:a87d1d16c79a564fb4812c',
    messagingSenderId: '1019726805573',
    projectId: 'my-barberia-7aa2a',
    storageBucket: 'my-barberia-7aa2a.firebasestorage.app',
    iosClientId: '1019726805573-tcm0dlmorlpn990lbr6tv9ijp2nuaku9.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5kPjw4esTbYMQLrHvJ0TtI-dnvQZrygw',
    appId: '1:1019726805573:web:b026d7d343949db8b4812c',
    messagingSenderId: '1019726805573',
    projectId: 'my-barberia-7aa2a',
    authDomain: 'my-barberia-7aa2a.firebaseapp.com',
    storageBucket: 'my-barberia-7aa2a.firebasestorage.app',
  );
}
